# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w4OA6pG0jWaK4vg0bdm9PyR-YOSpdpSV
"""
#Question 1
num1 = int(input("Enter the value of first number\n"))
num2 = int(input("Enter the vale of second number\n"))
num3 = int(input("Enter the value of third number\n"))
avg = (num1 + num2 + num3)/3

print("The average of these three numbers is" , avg)
#formula for average of three numbers a,b,c =(a+b+c)/3

#Question 2
#this is a program to compute a person's income tax
dependents = int(input("Enter the no. of dependents\n"))
gross_income = float(input("Enter the gross income\n"))
taxable_income =float(gross_income -10000-(3000*dependents))
income_tax = 0.2*taxable_income
print("Your net Income Tax is:" , income_tax)

#Question 3
#this is a prgram to store different data typ values into a list.
SID = int(input("Enter your SID\n"))
name = input("Enter your name\n")
gender = input("Enter ypur gennder, Use Gender values: 'F' , 'M' , 'U'(For Unknown)\n")
course_name = input("Enter your course name\n")
CGPA = float(input("Enter your CGPA\n"))
student = [SID, name, gender, CGPA]
print(student)

#Question 4
#This is a program to enter marks of 5 students into a list and display them in sorted manner.
student1 = int(input("Enter marks of first students\n"))
student2 = int(input("Enter the marks of second student\n"))
student3 = int(input("Enter the marks of third student\n"))
student4 = int(input("Enter the marks of fourth student\n"))
student5 = int(input("Enter the marks of fifth student\n"))
markslist = [student1, student2, student3, student4, student5]
markslist.sort()
print(markslist)

#Question 5
color = ["Red", "Green", "White", "Black", "Pink", "Yellow"]
color.remove("Black")
print(color)
color1 = ["Red", "Green", "White", "Black", "Pink", "Yellow"]
color1 = color1[:3] + ['Purple'] + color1[3+2:] #Index of 4th element is , performed slicing, to replace black and pink with purple
print(color1)
